### ISSUE TITLE
Make sure concurrency is working correctly

### ISSUE THREAD

**Issue by rlnsy** [ubc-systopia/pancast-code#10]
The SiLabs beacon and dongle implementations have no-ops in the LOCK and UNLOCK procedures. While things seem to be working fine now, we should figure out a way to provide proper mutual exclusion for shared data such as the encounter log and clocks.

**Comment by aasthakm** [comment]
@rlnsy can you elaborate on the issue?

**Comment by rlnsy** [comment]
Should make things lock-free (i.e. producer->consumer)

**Comment by aasthakm** [comment]
Not clear if there is a real problem here.
