### ISSUE TITLE
Implement live LED in Silabs beacon

### ISSUE THREAD

**Issue by nboufford** [ubc-systopia/pancast-code#33]
This will be useful if Silabs beacons are used for legacy advertising (ephemeral ID advertising) so that we can power them by battery and observe if the beacon is running. This has been implemented in the Silabs dongle, the same libraries and logic *should* be able to be used in the beacon.

**Comment by nboufford** [comment]
I tried to add the LED library and led.h file (same as the dongle) to the Silabs beacon code, but encountered build errors and was unable to fix them yet.

**Comment by aasthakm** [comment]
Fixed by commit [c2dabdc8ed](https://github.com/ubc-systopia/pancast-code/commit/c2dabdc8eda4e2d2f5e9c33c66bf9497c5e7c0d4)
