### ISSUE TITLE
Add enounter match flag per ID

### ISSUE THREAD

**Issue by nboufford** [ubc-systopia/pancast-code#36]
We keep track of number of matches and notify users of risk using the blinking LED. Additionally, it would be useful to have the matched encounters stored in flash.
There are a couple of issues that make this non-trivial:
1.  Adding a flag to the dongle storage encounter data structure in flash would mean loading the entire page on which the encounter resides, storing the page in memory, setting the flag, erasing the page in flash and rewriting. Allocating an in-memory buffer of page-size seems infeasible. If a workaround is found, or the available memory is increased this may be feasible.
2. Keeping another array in memory with flags corresponding to the encounter storage index is another option. This optin is also subject to memory constraints and it would have to be ensured that the indices in the array always match the encounter indices even when storage has been overwritten when the head wraps in the encounter log (this is likely okay but should be kept in mind).

**Comment by aasthakm** [comment]
Not important for now. We will do the matching from raw device logs offline.
